### ISSUE TITLE
bitfields: enhance formatting

### ISSUE THREAD

**Issue by Lotterleben** [knurling-rs/defmt#100]
currently `BitField`s are formatted as `{:#b}` but that may not be the most ergonomic option.
 
- display values in the "most readable" format but that's sort of arbitrary => binary as default; hex for multiples of 8?
- extra bonus points for underscores (readability++)

note:
you'll probably have to update en/decoding tests

**Comment by jonas-schievink** [comment]
This ties into the planned support for formatting modifiers like `{:x}`, so we have to figure out that plan first.

**Comment by japaric** [comment]
After RFC #270 bitfields are formatted using decimal notation by default. Other notation can be applied using display hints. Now that we have display hints I don't think we have to apply smart formatting by default (when no hint is specified) so I'm going to close this issue.
