### ISSUE TITLE
bitfield: further compression

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#101]
`info!("x={:10..14}", u16_value)` sends `u16_value` over the wire.
We can save bandwidth by sending only the higher byte `(u16_value >> 8) as u8`.

**Comment by Lotterleben** [comment]
Thinking out loud:
- `Codegen::new()` already truncates unneeded high bits https://github.com/knurling-rs/defmt/blob/main/macros/src/lib.rs#L764 so we could extend that to be a bit more sophisticated (shift octet overlaps into octets) and truncate low bits as well
- on the decoder side, we'd have to pay attention to `range.start` in https://github.com/knurling-rs/defmt/blob/main/decoder/src/lib.rs#L628 and shift+cast the data we've read using `self.bytes.read_u*...`accordingly
- my gut feeling is that cutting out "middle bytes" involves more headscratching esp. on the parser side (but fundamentally we have the info to decipher it in the fmt string)
