### ISSUE TITLE
Default timestamp

### ISSUE THREAD

**Issue by jonas-schievink** [knurling-rs/defmt#137]
Not all apps need timestamped logs, but currently every app must provide a `#[defmt::timestamp]` function.

Instead, we could provide a default zero timestamp source as a weak symbol, and have `#[defmt::timestamp]` override that. The host-side tooling would then omit time stamps if they're zero (or rather, until any timestamp is received that's non-zero).

We could also do something more fancy, like turning timestamps off altogether (so they'd take 0 Bytes of transferred data instead of at least 1 per log frame), but I feel like that ties into support for custom timestamp formats/encodings, which is a bigger feature.

**Comment by japaric** [comment]
Sounds good to me! There's some previous art around this in the cortex-m-rt repo; look for the  `HardFault_` function/symbol and the `PROVIDE` statements in the linker script.
