### ISSUE TITLE
defmt ignoring log when called as log argument

### ISSUE THREAD

**Issue by daschl** [knurling-rs/defmt#152]
Sorry for the confusing title, but here is what I found.

So let's say I have  a struct which has the following function:

```rs
pub fn read(&self) -> i32 {
        defmt::info!("read called");
}
```

Now when I call it like so:

```rs
let external_temp = external_temp_sensor.read();
defmt::info!("Temp is: {:i32}", external_temp);
```

Everything is fine and both info lines are printed. But when it it is called like this:

```rs
defmt::info!("Temp is: {:i32}",  external_temp_sensor.read());
```

Only  the "outer" info is logged and the inner `read called` info event is ignored and does not show up. Is this expected? I'm using probe-run 0.1.3 from master and defmt main branch from github as well (as described in the blog post on how to use it)

**Comment by japaric** [comment]
>  Is this expected?

no, this is a bug in the evaluation order. the arguments should be evaluated before we acquire the logger

the current expansion (`cargo expand`):
``` rust
defmt::info!("{:i32}", foo());
// ^ expands into
if true && true || !true && true {
    if let Some(mut _fmt_) = defmt::export::acquire() {
        match (defmt::export::timestamp(), &(foo())) {
            (ts, arg0) => {
                _fmt_.istr(&defmt::export::istr(match () {
                    #[cfg(not(target_arch = "x86_64"))]
                    () => {
                        #[link_section = ".defmt.info.{:i32}"]
                        #[export_name = "{:i32}@#7 bytes(139..169)"]
                        static DEFMT_LOG_STATEMENT: u8 = 0;
                        &DEFMT_LOG_STATEMENT as *const u8 as usize
                    }
                }));
                _fmt_.leb64(ts);
                _fmt_.i32(arg0);
                _fmt_.finalize();
                defmt::export::release(_fmt_)
            }
        }
    }
}
```
I think the correct order should be: evaluate log level (the `if true && ..` line); evaluate format arguments (`foo()`); `acquire` the logger; compute the `timestamp`; push data into logger (the `_fmt_` method calls); `release` call
