### ISSUE TITLE
Incomplete location table returned for `log` binary

### ISSUE THREAD

**Issue by jonas-schievink** [knurling-rs/defmt#159]
elf2table returns an incomplete location map for [`log.rs`](https://github.com/knurling-rs/defmt/blob/cf8a8e8328cd371c2d3ef3198ffb62c219e4dd6e/firmware/nrf52/src/bin/log.rs), leading to probe-run omitting all location info.

To reproduce, build `log.rs` (debug or release mode) and run it using `probe-run --defmt <ELF>`. Output:

> (BUG) location info is incomplete; it will be omitted from the output

**Comment by japaric** [comment]
This seems to be caused by the `{:?}` specifier; it seems to happen with any type (tested with `i32`)
