### ISSUE TITLE
Implement Format for i64/u64?

### ISSUE THREAD

**Issue by Dirbaio** [knurling-rs/defmt#160]
When trying to do this:

```rust
#[derive(defmt::Format)]
pub struct Instant {
    ticks: i64,
}
```

it fails because Format is not implemented for i64:

```
error[E0277]: the trait bound `i64: defmt::Format` is not satisfied
```

It would be great to be able to print 64-bit integers.

**Comment by MathiasKoch** [comment]
Would also be nice to have i128/u128 while at it.
