### ISSUE TITLE
implement Format for char

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#186]
this should work but triggers a compiler error right now:
``` rust
defmt::info!("x={:?}", 'a');
```
the `{:char}` format specifier would also need to be implemented

**Comment by japaric** [comment]
1. the easiest implementation could cast `char` to `u32` and send the 4 bytes
2. a better implementation would use invariants around UTF-8 to compress the data
3. alternative implementation: send the `char` as `[u8]`; would not compress as much as option 2

**Comment by jonas-schievink** [comment]
Seems like we could also leb128-encode the `char`. That way, any ASCII characters will only take up 1 Byte. I guess this is similar to using UTF-8.
