### ISSUE TITLE
how to implement Format for [T; N]? 

### ISSUE THREAD

**Issue by Dirbaio** [knurling-rs/defmt#206]
It would be quite handy if we could print arrays of any Format type. I had a go at implementing it, but it seems there is already a conflicting implementation for [u8; N] (overlaps because u8 is also Format).

I think this is not possible without specialization. What do we do?

- Not implement it?
- Remove the [u8] impl?
- use `min_specialization` behind a feature, so you can at least have both in nightly?

**Comment by japaric** [comment]
I would say remove the `[u8; N]` implementation so we can add the more general `[T; N]` implementation. The latter lets more code compile which is good. This will degrade the performance of `Format`-ing `[u8: N]` but that's an OK trade-off IMO. In any case, we haven't specialized `[u8]` either.

> use min_specialization behind a feature, so you can at least have both in nightly?

at the moment I would prefer not to rely on nightly features, even if those end up behind opt-in Cargo features
