### ISSUE TITLE
corrupted stream when mixing bools, options and arrays

### ISSUE THREAD

**Issue by Dirbaio** [knurling-rs/defmt#208]
```rust
    #[derive(defmt::Format)]
    pub struct DhcpRepr {
        pub broadcast: bool,
        pub a2: Option<[u8;6]>,
        pub a3: Option<[u8;6]>,
    }

    let mut dhcp_repr = DhcpRepr {
        broadcast: true,
        a2: Some([1, 2, 3, 4, 5, 6]),
        a3: None,
    };

    defmt::info!("print of death: {:?}", dhcp_repr);

```

if you stick it in the qemu firmware, it outputs this:

```
Error: couldn't decode all data (remaining: [70, 49, 6f, d, 1, b, 1, 2, 3, 4, 5, 6, d, 0, 1])
```

reproduces on latest `main` branch

**Comment by jonas-schievink** [comment]
I'm seeing this instead:

    0.000087 INFO print of death: DhcpRepr { broadcast: false, a2: Some([1, 3, 4, 5, 6, 15]), a3: 1 }

(which is arguably worse :smile: )

**Comment by jonas-schievink** [comment]
The derived `Format` impl contains a `_fmt_.finalize();` call, which is wrong. `finalize` should only be called by the logging macros once the whole frame has been encoded, otherwise we end up with additional compressed bool fields in the message.

**Comment by jonas-schievink** [comment]
Hmm, that does not seem to be the cause of this issue though. The same bug is in the decoder, so things end up working out fine.

**Comment by jonas-schievink** [comment]
Ah, the `Format` impl of `bool` also had a bug. Opened https://github.com/knurling-rs/defmt/pull/228 to fix this.
