### ISSUE TITLE
Using defmt on WSL provides a cryptic error message if git is missing

### ISSUE THREAD

**Issue by tl8roy** [knurling-rs/defmt#256]
While `libudev` and `libusb` are mentioned as dependencies, `git` is not. As such when trying to install `probe-run` or use defmt in a project you can get:
```
error: failed to run custom build command for defmt-decoder v0.1.1
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
This was hard to work out until `git` was mentioned in chat.
Once git was installed, it worked fine.

**Comment by japaric** [comment]
Thanks for the report. To double check: this was with a `--git` install and not a crates.io install?

In either case, installation should not error if `git` is not installed. `git` is not a dependency of `defmt` or `probe-run`.

**Comment by tl8roy** [comment]
This was a crates.io install.
'cargo install probe-run'

**Comment by harrysarson** [comment]
It looks like the build script of the defmt-decoder crate shells out to git here:

https://github.com/knurling-rs/defmt/blob/main/decoder/build.rs#L7

**Comment by japaric** [comment]
Yeah, the 2 build scripts in this repo should invoke git like [probe-run's build script](https://github.com/knurling-rs/probe-run/blob/519a03a9d70de6c4d1835a02581a581a319eaa59/build.rs#L15) does to avoid error-ing out on git not being installed.

**Comment by japaric** [comment]
This may be a more complicated than I hoped.
If we are doing a crates.io install then we should not depend on git at all. That's easy to fix.
If we are doing a git install then we do require the commit hash of the repo checkout by Cargo *even if there's no git command line tool installed on the system*. That's the tricky part. Making the build script depend on the libgit2 crate will be headache to install for Windows users.

**Comment by japaric** [comment]
wait, I think we can read the `.git/ORIG_HEAD` file instead of shelling out to git
