### ISSUE TITLE
Don't trust UTF8 from the target

### ISSUE THREAD

**Issue by Dirbaio** [knurling-rs/defmt#262]
If the target prints a string with invalid utf8, this happens:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [117, 226, 161, 158, 1, 43, 136, 162, 158, 1, 42, 21, 43, 160, 162, 158, 1, 42, 9, 43, 181, 162, 158, 1, 42, 44, 236, 186, 158, 1, 42, 12, 92, 102, 57, 92], error: Utf8Error { valid_up_to: 6, error_len: Some(1) } }', /home/dirbaio/.cargo/git/checkouts/defmt-4f58110b0615f1de/5e30729/decoder/src/lib.rs:802:68
```

I'm not sure why the hell is my target sending invalid utf8, but in any case defmt shouldn't crash. Not sure if it'd be best to report decoding error, or try to "fix" the string by removing invalid bytes.

**Comment by jonas-schievink** [comment]
Thanks for the report! Fix is up at https://github.com/knurling-rs/defmt/pull/264.
