### ISSUE TITLE
docs.rs fails to build defmt

### ISSUE THREAD

**Issue by Dirbaio** [knurling-rs/defmt#285]
Currently you can't view defmt docs on docs.rs: https://docs.rs/crate/defmt/0.1.2
Here's the build failure https://docs.rs/crate/defmt/0.1.2/builds/319575

**Comment by jonas-schievink** [comment]
I suppose we should not build for `thumbv6m-none-eabi` then, since it lacks atomics and thus `alloc::sync`.
