### ISSUE TITLE
defmt-test: Allow use in test module

### ISSUE THREAD

**Issue by Sh3Rm4n** [knurling-rs/defmt#289]
Hey, I'd like to propose a feature request:

Support use statements in the `#[defmt_test::tests]` macro. 
It is pretty common to import the output scope via `use super::*;`. 
But this is currently not possible:

```patch
 testsuite/tests/test.rs | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/testsuite/tests/test.rs b/testsuite/tests/test.rs
index d1002ce..7a8d75b 100644
--- a/testsuite/tests/test.rs
+++ b/testsuite/tests/test.rs
@@ -7,6 +7,8 @@ use {{crate_name}} as _; // memory layout + panic handler
 // feature)
 #[defmt_test::tests]
 mod tests {
+    use super::*;
+
     #[test]
     fn assert_true() {
         assert!(true)
```

```log
$ cargo test
   ...
   Compiling use-test v0.1.0 (/tmp/use-test)
   Compiling testsuite v0.1.0 (/tmp/use-test/testsuite)
error: only function items are allowed
  --> testsuite/tests/test.rs:10:5
   |
10 |     use super::*;
   |     ^^^

error: aborting due to previous error

error: could not compile `testsuite`
```

As we can see, this case is currently just not taken into consideration:

https://github.com/knurling-rs/defmt/blob/2657a8db30a67c7f225611e2c14cb2759df876da/firmware/defmt-test/macros/src/lib.rs#L133-L138

The current workaround I use, it to declare the `use` statement in the function scope, e.g.

```patch
 #[defmt_test::tests]
 mod tests {
-    use super::*;
-
     #[test]
     fn assert_true() {
+        use super::*;
+         
         assert!(true)
```

If you point me into the right directions I could try to implement this
feature myself. But I've no experience writing procedural macros, so any help
is appreciated :)

**Comment by japaric** [comment]
This would be a great addition!

I think in terms of implementations this should work:

1. collect `use` items ("imports") in a vector in this `for` loop (the imports correspond to the `Item::Use` variant): https://github.com/knurling-rs/defmt/blob/2657a8db30a67c7f225611e2c14cb2759df876da/firmware/defmt-test/macros/src/lib.rs#L37

2. include those imports in the output right before this line: https://github.com/knurling-rs/defmt/blob/2657a8db30a67c7f225611e2c14cb2759df876da/firmware/defmt-test/macros/src/lib.rs#L197 -- the [`quote!`] syntax for lists (e.g. vectors) is `#(#list)*`; you'll want to interpolate the whole vector you collected in (1)

[`quote!`]: https://docs.rs/quote/1.0.7/quote/macro.quote.html

3. check the changes using [`cargo-expand`]. Starting from the app-template, use the `[patch]` section in the root `Cargo.toml` to use your local version

[`cargo-expand`]: https://crates.io/crates/cargo-expand

``` toml
[patch.crates-io]
# NOTE change the `file` path and the `branch` here to match your local setup
defmt = { git = "file:///home/japaric/rust/defmt", branch = "allow-imports" }
defmt-rtt = { git = "file:///home/japaric/rust/defmt", branch = "allow-imports" }
# (..)
```

With those changes, run `cargo expand -p testsuite --test test` to see the expansion of the `testsuite/tests/test.rs` file. Modify `test.rs` file and rerun `cargo-expand` to see if imports are being included in the output.

NOTE: all changes in you your local `defmt` repository must be committed or `app-template` won't pick them up! Also, you need to run `cargo update` from `app-template` to make it pick up new commits in your local `defmt` repository
