### ISSUE TITLE
`defmt-print`: remove supported version from help output

### ISSUE THREAD

**Issue by Lotterleben** [knurling-rs/defmt#353]
As mentioned by @japaric in https://github.com/knurling-rs/probe-run/pull/133 , https://github.com/knurling-rs/probe-run/issues/131 applies to `defmt-print` too.

Modification should probably take place in https://github.com/knurling-rs/defmt/blob/574f77f05f0d72f905c8955cb7a652fb4f91726e/print/src/main.rs#L95

Opening this as another issue so we don't forget.

**Comment by japaric** [comment]
PR #352 will fix this

**Comment by Lotterleben** [comment]
oh whoops

**Comment by jonas-schievink** [comment]
#352 was merged
