### ISSUE TITLE
simplify CI: remove macos special case

### ISSUE THREAD

**Issue by spookyvision** [knurling-rs/defmt#358]
currently the CI tests work around `cortex-m-rt` not compiling on macos by adding a special case. This can be removed as soon as a new version of `cortex-m-rt` is released that contains https://github.com/rust-embedded/cortex-m-rt/pull/306

**Comment by japaric** [comment]
PR #364 removed the OS special casing by changing CI to not compile cortex-m dependent crates to the host.
