### ISSUE TITLE
pin dependency versions

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#378]
all dependencies that are in this repo ('path' dependencies) and have the "unstable" feature (e.g. defmt-decoder) should be specified in Cargo.toml using an exact version, e.g. `=0.1.2`.
that way we'll be able to make breaking changes in the "unstable" API in patch versions

**NOTE** this also needs to be in `probe-run`

**Comment by jonas-schievink** [comment]
reopening, the probe-run changes are still outstanding
