### ISSUE TITLE
defmt-test: README (Basic Usage section) should be updated

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#402]
Steps 1 and 2 refer to an old version of app-template that didn't use `defmt-test`. I think quite some time has passed so those two steps (and step 0) can be removed.

**Comment by Urhengulas** [comment]
I am not sure if I understand the issue. Can you please rephrase it?

**Comment by japaric** [comment]
> Steps 1 and 2 (and step 0)

[in this README file](https://github.com/knurling-rs/defmt/blob/55fcab61495b1651e2d157e79b50277f33c151ef/firmware/defmt-test/README.md#basic-usage)

should be removed

**Comment by Urhengulas** [comment]
> > Steps 1 and 2 (and step 0)
> 
> [in this README file](https://github.com/knurling-rs/defmt/blob/55fcab61495b1651e2d157e79b50277f33c151ef/firmware/defmt-test/README.md#basic-usage)
> 
> should be removed

I got that it is about that file.

But I understood these steps to also be for people adding `defmt-test` to their existing project. But in that case they probably can refer to `app-template` and copy the stuff over from there.
