### ISSUE TITLE
defmt.ferrous-systems.com is outdated (?)

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#404]
at least the [timestamp section](https://defmt.ferrous-systems.com/timestamp.html) still documents the `#[defmt::timestamp]` attribute.

**Comment by jonas-schievink** [comment]
The new stuff is on https://defmt-next.ferrous-systems.com/

**Comment by jonas-schievink** [comment]
How/Where did we set up the different subdomains?

**Comment by jonas-schievink** [comment]
This is now fixed, but the Netlify setup is still evil
