### ISSUE TITLE
defmt-test v0.2.0 depends on defmt-test-macros v0.1.1

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#417]
defmt-test-macros v0.1.1 was released 3 months ago and doesn't include support for `Result` return types so this doesn't compile with `defmt-test` v0.2:

``` rust
#[test]
fn foo() -> Result<(), ()> { //~ error
    Ok(())
}
```

``` console
error: `#[test]` function must have signature `fn([&mut Type])` (parameter is optional)
```

**Comment by jonas-schievink** [comment]
defmt-test-macros 0.2.0 was missed during the 0.2 release, it's still on 0.1.1
