### ISSUE TITLE
outdate NOTE in defmt.ferrous-systems.com

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#419]
The note in the front page of https://defmt.ferrous-systems.com/ says:

> NOTE this hosted version of the defmt book corresponds to the unreleased defmt v0.2.0, which is currently only available as a git dependency. If you are looking for defmt v0.1.x's documentation head to https://defmt.ferrous-systems.com.

but v0.2.0 has already been released

**Comment by Urhengulas** [comment]
Should we maybe still keep a note for `defmt-next.f-s.com` indicating that this is served from `main`?
