### ISSUE TITLE
add knurling logo to the book

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#420]
also link to the [knurling website](https://knurling.ferrous-systems.com/) and the GitHub sponsors page.

by 'the book' I mean https://defmt.ferrous-systems.com/

**Comment by Urhengulas** [comment]
There is the option to add the logo to the header of every page via ([link](https://rust-lang.github.io/mdBook/format/theme/index.html)), but I think this is to much:

![Screenshot from 2021-07-05 18-37-46](https://user-images.githubusercontent.com/37087391/124500475-23dbd180-ddc0-11eb-9165-ac34d0694525.png)
