### ISSUE TITLE
defmt-test: attribute "(1/n) running `test`..." messages to the test in question

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#425]
given this test file

``` rust
#[defmt_test::tests] // <- line 8
mod tests {
    #[test]
    fn a() {
        trace!("A");
    }

    #[test]
    fn b() {
        trace!("B");
    }
}
```

`probe-run` output looks like this:

``` console
$ cargo t
0.000000 INFO  (1/2) running `a`...
└─ foo::tests::__defmt_test_entry @ tests/foo.rs:8
0.000000 TRACE A
└─ foo::tests::a @ tests/foo.rs:12
0.000000 INFO  (2/2) running `b`...
└─ foo::tests::__defmt_test_entry @ tests/foo.rs:8
0.000000 TRACE B
└─ foo::tests::b @ tests/foo.rs:17
0.000000 INFO  all tests passed!
└─ foo::tests::__defmt_test_entry @ tests/foo.rs:8
```

the location info shown on the "running" lines is misleading because it points to the `#[tests]` attribute. I think it would be better if no location info was shown on those:

``` console
$ cargo t
0.000000 INFO  (1/2) running `a`...
0.000000 TRACE A
└─ foo::tests::a @ tests/foo.rs:12
0.000000 INFO  (2/2) running `b`...
0.000000 TRACE B
└─ foo::tests::b @ tests/foo.rs:17
0.000000 INFO  all tests passed!
└─ foo::tests::__defmt_test_entry @ tests/foo.rs:8
```

if the "running" lines had custom tags (as suggested in knurling-rs/probe-run#167) then I think this could be implemented in `probe-run`.

I guess the other option is to crate a set of (private?) `defmt` logging macros that do *not* include location info and then use those from the `defmt-test` proc macro.

**Comment by jonas-schievink** [comment]
Mentoring instructions:

The following code generated by the `#[defmt_test::tests]` macro needs its span set to that of `test.func.sig.ident`:

https://github.com/knurling-rs/defmt/blob/298e1add752712646edee173d7a41d018487aa3c/firmware/defmt-test/macros/src/lib.rs#L233
