### ISSUE TITLE
μ (U+03BC) vs. µ (U+00B5)

### ISSUE THREAD

**Issue by Urhengulas** [knurling-rs/defmt#434]
We are using the micro sign (`µ`) for the `µs` display hint ([see defmt-book](https://defmt.ferrous-systems.com/hints.html)). If a user accidentally uses the greek letter mu (`μ`) which looks the same on most fonts, they get an not super helpful `error: unknown display hint: "μs"`.

It woud be nice to have an error message more along the lines of
>  error: unknown display hint: "μs"; did you mean "µs"?

**Comment by MathiasKoch** [comment]
Why not just use `us` ?

**Comment by japaric** [comment]
>Why not just use us ?

I would vote for accepting `us` (and maybe deprecating / removing the *mu* version in the future)

**Comment by Urhengulas** [comment]
> Why not just use `us` ?

Agree!
