### ISSUE TITLE
make a defmt-test release to update README on crates.io

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#461]
last release was 2 months ago. the latest version of the defmt-test README contains an awesome GIF of it in action.
The [crates.io version](https://crates.io/crates/defmt-test/0.2.1), on the other hand, has outdated steps in it.
Let's do a new crate release to put that cool GIF on crates.io.
cc @Urhengulas

**Comment by Urhengulas** [comment]
I am on this. But I already noticed that the gif is already part of the latest `defmt-test` release and just can't be displayed.
