### ISSUE TITLE
write a 0.2.x -> 0.3.0 migration guide

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#530]
0.3 will include several breaking changes. this guide would explain how to migrate code that uses defmt 0.2.x to 0.3.0

example of a migration guide: https://rtic.rs/0.5/book/en/migration.html

**Comment by Urhengulas** [comment]
Should this guide only list breaking changes, or also new features?

**Comment by japaric** [comment]
the focus should be on *fixing* things that no longer compile or no longer behave the same: changes in syntax; changes in API; `defmt-*` Cargo features no longer being needed; `DEFMT_LOG` now being a thing. It should offer a quick fix (e.g. to get the old behavior use `DEFMT_LOG=info cargo r`), ideally in the form of a `diff` when code is involved; the migration guide can defer / link to other dedicated sections of the book for details about new features (e.g. ISO timestamp display hint).
