### ISSUE TITLE
Include crate name in symbol name

### ISSUE THREAD

**Issue by jonas-schievink** [knurling-rs/defmt#532]
Currently, the symbol name includes the Cargo package, the defmt tag and data, and the "disambiguator", which is a crate-unique identifier. However, a Cargo package can contain many crates, so to be safe we should also include the *crate* name (via `CARGO_CRATE_NAME`) in the symbol name.

Another unclear edge case is what happens when crates are renamed in a downstream `Cargo.toml` (https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml). It seems like this might let you pull in two crates with the same crate *and* package name, but a different Cargo version, so maybe that should also be included.

**Comment by Urhengulas** [comment]
Context: This issue was raised due to the following comment (https://github.com/knurling-rs/defmt/pull/528#discussion_r669640008):
> > should disambiguate macro invocations within a crate.
>
> "within a crate" but then we are pairing this with CARGO_PKG_NAME which is the package name, not the crate name, to create a unique key within the entire dependency graph. shouldn't we be using CARGO_CRATE_NAME? this is not something that should be addressed in this PR but maybe there should be an issue to consider using the 'crate name' rather than the 'package name' OR both -- you have mention that build scripts (build.rs) crates are always named build_script; though that crate won't be linked into the final binary.
