### ISSUE TITLE
Update app-template to `defmt 0.3`

### ISSUE THREAD

**Issue by Urhengulas** [knurling-rs/defmt#566]
We should update the `knurling-rs/app-template` to `defmt 0.3` and release the new template at the same time as `defmt`.

This issue only exists here, so we can add it to the milestone. There is also https://github.com/knurling-rs/app-template/issues/54.

**Comment by Lotterleben** [comment]
blocked on release being ready

**Comment by japaric** [comment]
submitted a draft PR: knurling-rs/app-template#56
