### ISSUE TITLE
`defmt::println` messages have a leading space when timestamps are disabled

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#602]
Steps to reproduce:
- start from `app-template` (`main` branch)
- configure it to use git version of `defmt` crates
- remove the `defmt::timestamp!` item from `src/lib.rs`
- modify `src/bin/hello.rs` to use `println!`

``` rust
defmt::println!("Hello, world!");
```

This outputs:

``` console
 Hello, world!
└─ hello::__cortex_m_rt_main @ src/bin/hello.rs:8
```

Ideally, it should output: (the `H` is exactly on top of the "corner pipe")

``` console
Hello, world!
└─ hello::__cortex_m_rt_main @ src/bin/hello.rs:8
```

to match the other logging macros, e.g. the `levels` example produces:

``` console
ERROR error
└─ levels::__cortex_m_rt_main @ src/bin/levels.rs:12
```

cc @justahero

**Comment by jonas-schievink** [comment]
Problem lies here:

https://github.com/knurling-rs/defmt/blob/4e594035eb6b954ad171c093959ab4bc8ca47525/decoder/src/log.rs#L59

The fix is to make `timestamp` an `Option<String>`in that function and only add the space in that branch when it's `Some`.
