### ISSUE TITLE
`Strip` in `release` with defmt

### ISSUE THREAD

**Issue by mryndzionek** [knurling-rs/defmt#653]
In `release` I would like to use `strip` and remove `defmt` entirely, but then I get:
```rs
Error: `.defmt` section found, but no version symbol - check your linker configuration
```

**Comment by jonas-schievink** [comment]
`strip` has a `--remove-section` flag, have you tried that?

**Comment by mryndzionek** [comment]
It turns out that `strip` works okay, but the Error is from `probe-run`...

**Comment by mryndzionek** [comment]
I made some progress using `--only-keep-debug`, but now `probe-run` returns:
```
Error: vector table section is too short. (has length: 0 - should be at least 16)
```

**Comment by jonas-schievink** [comment]
`--only-keep-debug` is the opposite of stripping debug info, it removes all non-debug data

**Comment by mryndzionek** [comment]
Closing this for now. It seems that stripping won't get me much in `--release`
