### ISSUE TITLE
CI failure: package `defmt-itm` is a member of the wrong workspace

### ISSUE THREAD

**Issue by Urhengulas** [knurling-rs/defmt#685]
Since a few days the the CI started failing the `qemu-snapshot (nightly)` job. Some of the snapshot test fail with following error message. I was able to reproduce the error locally by running:

```console
$ cd path/to/defmt/firmware/qemu
$ DEFMT_LOG=trace cargo +nightly rb dbg
error: package `/path/to/defmt/firmware/defmt-itm/Cargo.toml` is a member of the wrong workspace
expected: /path/to/defmt/firmware/Cargo.toml
actual:   /path/to/defmt/Cargo.toml
```
Some observations:
- The failure is random. Sometime the test succeeds, sometimes it does not.
- Running `cargo clean` before the test, seems to increase the likelihood of success, but it still fails sometimes.
- It only fails on nightly. I didn't bisect the exact version when it started to fail, yet.

I will disable the test for the moment, but we should try to fix this and enable it again.

**Comment by Urhengulas** [comment]
If I remove `defmt-itm` from the members list in `firmware/Cargo.toml` the error message changes `defmt-itm` to `defmt-rtt` to:

```console
$ DEFMT_LOG=trace cargo +nightly rb dbg
error: package `/path/to/defmt/firmware/defmt-rtt/Cargo.toml` is a member of the wrong workspace
expected: /path/to/defmt/firmware/Cargo.toml
actual:   /path/to/defmt/Cargo.toml
```

`defmt-itm` is the alphabetically first and `defmt-rtt` is the alphabetically second. So I don't think it is something about `defmt-itm` in particular, but just the whole workspace.

**Comment by japaric** [comment]
appears to be an upstream bug. reported it in rust-lang/cargo#10864. as a workaround we can pin the nightly to `nightly-2022-07-10` in CI
