### ISSUE TITLE
WARN  (BUG) location info is incomplete in ESP32

### ISSUE THREAD

**Issue by farbodpm** [knurling-rs/defmt#727]
Hi,
I am trying to parse data from my esp32 board using defmt project bug I faced this error.
"WARN  (BUG) location info is incomplete; it will be omitted from the output"

**Comment by farbodpm** [comment]
I fixed it ... . there was no problem.  but I think the commit is a little unclear.

**Comment by Urhengulas** [comment]
Hi @farbodpm, how would you phrase it more clearly? 😄
