### ISSUE TITLE
feature: defmt-print detect executable changing

### ISSUE THREAD

**Issue by d3zd3z** [knurling-rs/defmt#794]
When debugging using the JLink debugger, it remains attached, and is able to (eventually) detect that the target has reset. However, if using defmt-print tcp to this target, it doesn't notice that the executable has changed, and will continue trying to decode messages from the old symbols. I'm not sure the best way to handle this, but just wanted to think about how it could be handled.

**Comment by jonathanpallant** [comment]
We might be able to watch the file and reload it if it changes? You could also do something similar using a package like inotify-tools in the interim.

**Comment by Urhengulas** [comment]
Fixed by https://github.com/knurling-rs/defmt/pull/807/.
