### ISSUE TITLE
[Defmt-test] `defmt-test` readme is out of sync with its `defmt-test-macros` dependency

### ISSUE THREAD

**Issue by ithinuel** [knurling-rs/defmt#801]
`defmt-test` still relies on `defmt-test-macros 0.3.0` which lacks `#[before_each]`/`#[after_each]` amongst other things despite these macro being present in `defmt-test` documentation/readme.

**Comment by Urhengulas** [comment]
Just published `defmt-test v0.3.2` which includes the changes.
