### ISSUE TITLE
Dump log strings to local file

### ISSUE THREAD

**Issue by not-matthias** [knurling-rs/defmt#802]
What do you think about placing the .defmt section on disk, rather than embedding it inside the binary? This would make parsing a lot easier since you don't have to implement different binary formats (see #463 ). 

This also has additional benefits: 
- Save storage by not including debug strings in the binary (they aren't used anyways)
- Don't give logs to possible attackers that could analyze your code

---

To give some more context about my situation: I'm planning on using defmt for my Intel hypervisor running as Windows kernel driver. I already managed to get defmt to run, but I need to decode the logs now. One option would be to parse the PE file, but dumping it directly to disk would be much easier.

**Comment by jonathanpallant** [comment]
I'll be honest, that seems like a niche use-case (as compared to getting logs out of a Cortex-M microcontroller). Perhaps `rust-objdump` can help you get what you need though? It seems to support .EXE files.

> Save storage by not including debug strings in the binary (they aren't used anyways)

The strings are placed in an ELF section which is not loaded into Flash on the target. The size of the ELF file itself is usually of no consequence.

> Don't give logs to possible attackers that could analyze your code

If you don't want to distribute the ELF file, you don't have to. There will be no defmt strings in the target device's Flash memory.
