### ISSUE TITLE
Color in the format string is not propagated

### ISSUE THREAD

**Issue by korken89** [knurling-rs/defmt#806]
Hi,

I tried to add color to the format string for `defmt_decoder` in `probe-rs` to make it more readable, but the color specification on the string did not propagate properly.
Here is the testing PR in `probe-rs`: https://github.com/probe-rs/probe-rs/pull/2063

This would help readability a lot. Is there someway to make this happen or does `defmt_decoder` need extension?

This also broke in `probe-run v0.3.9 -> v0.3.10` where the file info part of the printing got the color wrong.

`probe-run v0.3.9`:
![image](https://github.com/knurling-rs/defmt/assets/913109/0be7a157-3cf6-45a2-84f1-b5afbcbc2f54)

`probe-run v0.3.10` and `probe-rs run`:
![image](https://github.com/knurling-rs/defmt/assets/913109/2375c453-0865-4f19-b3cd-3443b6cc7510)

**Comment by Urhengulas** [comment]
There was a new release on 05.02.2024. Can you check if it works now?

**Comment by Urhengulas** [comment]
I just tried `{L} {s} ({f:dimmed})` and with the current defmt release behaves as expected.
