### ISSUE TITLE
Define an MSRV

### ISSUE THREAD

**Issue by MabezDev** [knurling-rs/defmt#819]
The readme states the MSRV is the latest stable Rust, but I think now that defmt is a staple in the embedded-rust ecosystem you should consider picking an MSRV and only bumping when needed (and subsequently bumping the version in a semver compatible way too).

**Comment by Urhengulas** [comment]
How is this handled usually? Do we build and test against the latest stable and the MSRV in CI? 

> subsequently bumping the version in a semver compatible way too

What do you mean by that? Would you consider it a breaking change if the MSRV is bumped?

**Comment by MabezDev** [comment]
>How is this handled usually? Do we build and test against the latest stable and the MSRV in CI?

Yes.

> What do you mean by that? Would you consider it a breaking change if the MSRV is bumped?

There doesn't seem to be a clear answer here, at least upstream Rust hasn't taken a stance. In general though, unless defmt needs to opt in to new features, keeping MSRV as latest STABLE seems a bit silly, especially since defmt is used so widely in the ecosystem.

**Comment by thejpster** [comment]
I suspect we'll tie the MSRV to Ferrocene's upstream equivalents.

**Comment by Urhengulas** [comment]
@jonathanpallant [said](https://github.com/knurling-rs/defmt/issues/866#issue-2542951460):
> Our effective MSRV is currently Ferrocene 24.05 (Rust 1.76.0) and so we should clarify that in the README.

**Comment by Urhengulas** [comment]
Fixed by https://github.com/knurling-rs/defmt/pull/871.
