### ISSUE TITLE
decoder: pre-processed Arg (e.g. real structs instead of nested format strings)

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#82]
The existing `Format` (and the upcoming `FormatSlice`) variants are a bit problematic/annoying because they require re-parsing the format string during display and (further) serialization.

If instead we assume that `Arg` will either be a primitive, a struct or a enum (the last two could recursively contain a struct or enum but ultimately contain primitives) then we can pre-process the `Arg` and flatten it in some cases.
A flattened `Arg` variant may look like this:

``` rust
// (more optimized representations are possible:
//  e.g. interned strings or interned struct layouts)
enum Val<'t> {
    Ixx(i64),
    Uxx(u64),
    Bool(bool),
    F32(f32),
    Struct {
        name: String,
        fields: HashMap<String, Val>,
    },
    // Enum, etc.
}
```

This structure is easier to print and serialize, into say JSON, for inter-op with front-ends.

With this representation, data like this:

``` rust
info!("x={:?}", 42u8);
[
    $index1, // "x={:?}"
    $index2, // "{:u8}"
    42,
]
```

can be processed into `Val::Uxx(42)` (last two bytes) -- today that would be `Arg::Format { format: "{:u8}", args: [Arg::Uxx(8)] }`

And data like this:

``` rust
[
    $index1, // "X {{ y: {:?} }}"
    $index2, // "Y {{ z: {:u8} }}"
    42,
]
```

can be decoded into (hypothetical hash map literal) `Struct { name: "X", fields: { "y": Struct { name: "Y", fields: { "z": Uxx(42) } }  } }` -- today that's two nested `Arg::Format` values

Then log frames can become something like this:

``` rust
struct Frame<'t> {
    pub level: Level,
    // Processed format string
    pub pieces: Vec<Piece<'t>>,
    pub timestamp: u64,
    pub args: Vec<Val<'t>>,
}

enum Piece<'t> {
    Str(&'t str),
    // index into `self.args` (simplified: bitfields make this more complex)
    Param(usize),
}
```

But to make this work we need to constrain `Format` implementations.
Right now they can be too free-form because `write!` is public.
The user could write:

``` rust
struct S {
    x: u8,
}

impl Format {
    fn format(&self, f: &mut Formatter) {
        write!(f, "S; x = {:u8};", self.x)
    }
}
```

The chosen format string wouldn't match the `decoder` expectation (`S {{ x: {:u8} }}`) and it would not be possible to process it as a `Val::Struct`

To avoid that issue we can remove `write!` from the public API and instead provide customization of the `Format` implementation through attributes (like `serde` does)
.
For example, `#[rename]` could be used to rename fields and `#[skip]` could be used to skip fields.

``` rust
// "S {{ loop: {:u8} }}"
#[derive(Format)]
struct S {
    #[rename = "loop"]
    _loop_: u8,
    #[skip]
    secret_key: [u8; 16],
}
```

Thoughts? @jonas-schievink

**Comment by jonas-schievink** [comment]
I think we can close this – structural logging can now be implemented using the `defmt_derive` tag, while we also have manual `Format` impls that can use `write!`.
