### ISSUE TITLE
cargo-embed produces broken output

### ISSUE THREAD

**Issue by FlareFlo** [knurling-rs/defmt#823]
When running my [learning project](https://github.com/FlareFlo/stm32-rtic/tree/defmt-rtt-issue) using cargo-embed, the defmt output appears to be complete garbage.
Running with `cargo-embed --release`:
[![asciicast](https://asciinema.org/a/uIL7fHe5225hoFM0drl0pNvT7.svg)](https://asciinema.org/a/uIL7fHe5225hoFM0drl0pNvT7)
When running with probe-rs directly after the output appears to be correct:
![image](https://github.com/knurling-rs/defmt/assets/78537307/0fb2da26-819d-4659-b2ef-544f09b9f0bd)
I hope my project is minimal enough to help with reproducing the issue. The hardware used is an STM32F411CEb with the STLink V2.0.
Cargo-embed is on version 0.13.0
probe-rs is on version 0.23.0

**Comment by Urhengulas** [comment]
Can you please report this at probe-rs?

**Comment by FlareFlo** [comment]
Done
