### ISSUE TITLE
Online defmt book needs to be updated

### ISSUE THREAD

**Issue by plaes** [knurling-rs/defmt#851]
Currently published [defmt book](https://defmt.ferrous-systems.com/) seems to be seriously outdated as its version is: `commit e1fd1e6 on 2024-02-07 19:08:44`.

**Comment by Urhengulas** [comment]
On it

**Comment by andershedberg** [comment]
I tried to look in the document to see how the logs actually look, and that is sadly missing. No examples at all of logfiles.

**Comment by Urhengulas** [comment]
> I tried to look in the document to see how the logs actually look, and that is sadly missing. No examples at all of logfiles.

In the display hint chapter you can see the output as comments in the code: https://defmt.ferrous-systems.com/hints.

**Comment by Urhengulas** [comment]
We should switch from netlify to github pages using https://github.com/actions/upload-pages-artifact and https://github.com/actions/deploy-pages.

**Comment by Urhengulas** [comment]
The defmt book is now hosted on cloudflare and is tracking the main branch.
