### ISSUE TITLE
u16 can not be used as type specifier

### ISSUE THREAD

**Issue by hvraven** [knurling-rs/defmt#882]
I tried to send an u16 slice or array using `{=[u16]}` (or `{=[u16;3]}` as documented in the defmt book. However I got a compiler error complaining about `[u16]` being an invalid type specifier. Same problem for `u32`. `u8` compiles and runs without issues. Reduced test case below. I am using defmt 0.3.8 with rust/cargo 1.82.0

```rust
use defmt::*;

fn main() {
    let arr :[u8; 3] = [0,1,2];

    debug!("{=[u8]}", arr);

}
```

**Comment by jonathanpallant** [comment]
`=[u8]` is supported as a special case because people *really often* want to log byte arrays on embedded systems (network packets, disk sectors, HID frames, etc). `=[u16]`, etc, is not supported at this time.
