### ISSUE TITLE
book: interning: chapter contains invalid linker script

### ISSUE THREAD

**Issue by xobs** [knurling-rs/defmt#886]
The book [contains an example of interning](https://github.com/knurling-rs/defmt/blob/60ea3a554adf91551588d2678488628bf4601950/book/src/interning.md?plain=1#L27). This contains the following line:

```
    : 0 /* <- start address of this section */
```

If you try to use this, it fails:

```
          rust-lld: error: /Users/seancross/Code/test/link.ld:131: { expected, but got 0
          >>>   .my_custom_section (INFO) : 0 {
          >>>                               ^
          Error: "Linker exited with status 1"
```

It looks like the number should go after `.my_custom_section` but before `(INFO)` like it does in `defmt.x.in`

**Comment by jonathanpallant** [comment]
Thanks! See https://github.com/knurling-rs/defmt/pull/887 for the fix.
