### ISSUE TITLE
Remove the CHANGELOG checker

### ISSUE THREAD

**Issue by jonathanpallant** [knurling-rs/defmt#896]
CHANGELOGs, as per https://keepachangelog.com/en/1.1.0/ are:

> a file which contains a curated, chronologically ordered list of notable changes for each version of a project.

The changelog check in the CI forces me to add a change log entry, even for non-notable changes. We should relax it, or remove it.

**Comment by Urhengulas** [comment]
The changelog check does allow to skip adding something to the changelog by adding a "skip-changelog" label. I kinda like that that decision needs to be done consciously so we do not forget about adding something to the changelog.

**Comment by jonathanpallant** [comment]
OK, that works for me.
